website/auth.py
from flask import Blueprint, flash, render_template, request, url_for, redirect
from werkzeug.security import generate_password_hash, check_password_hash
from .models import User
from .forms import LoginForm, RegisterForm
from flask_login import login_user, login_required, logout_user
from . import db

# Create a blueprint - make sure all BPs have unique names
auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm()
    error = None

    if (login_form.validate_on_submit()==True):
        user_name = login_form.user_name.data
        password = login_form.password.data

        user = db.session.scalar(db.select(User).where(User.name==user_name))

        if user is None:
            error = 'Incorrect user name'
        elif not check_password_hash(user.password_hash, password):
            error = 'Incorrect password'

        if error is None:
            login_user(user)
            next_url = request.args.get('next')  # Get the URL from where the login page was accessed

            if not next_url or not next_url.startswith('/'):
                return redirect(url_for('main.index'))

            return redirect(next_url)
        else:
            flash(error)

    return render_template('user.html', form=login_form, heading='Login')

#Function for registering a new user to the site and storing it within the database
@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    registration_form = RegisterForm()

    if registration_form.validate_on_submit():
        user_name = registration_form.user_name.data
        password = registration_form.password.data
        email = registration_form.email_id.data
        contact = registration_form.contact_no.data
        address = registration_form.address.data

        user = User.query.filter_by(name=user_name).first()

        if user:
            flash('Username already exists, please try a different one')
            return redirect(url_for('auth.register'))

        password_hash = generate_password_hash(password)
        new_user = User(name=user_name, password_hash=password_hash, emailid=email, contact=contact, address=address)

        db.session.add(new_user)
        db.session.commit()

        return redirect(url_for('main.index'))
    else:
        return render_template('user.html', form=registration_form, heading='Register')


    
#Logs the user out of their account
@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

website/views.py
from flask import Blueprint, render_template, request, url_for, redirect
from .models import Event, Booking
from . import db
from sqlalchemy import or_
from flask_login import login_required, current_user

main_bp = Blueprint('main', __name__)

@main_bp.route('/')
def index():
    # Predefined list of all possible genres
    all_genres = ['Rock', 'Pop', 'Hip-Hop', 'Country', 'Jazz', 'Blues', 'Classical']

    # Get genre query parameter, defaults to None if not provided
    genre_query = request.args.get('genre', None)
    search_query = request.args.get('search', '')

    if genre_query:
        # Filter events by the provided genre
        events = Event.query.filter_by(genre=genre_query).all()
    elif search_query:
        # If there is a search query, filter events based on the search term
        query = "%" + search_query + "%"
        events = db.session.query(Event).filter(
            or_(Event.name.like(query), Event.description.like(query))
        ).all()
    else:
        # Get all events if no genre or search query is provided
        events = Event.query.all()
    
    return render_template('index.html', events=events, genres=all_genres, search_query=search_query)


@main_bp.route('/search')
def search():
    # Redirect to the index with the search term as a query parameter
    return redirect(url_for('main.index', search=request.args.get('search', '')))

    
ROWS_PER_PAGE = 6

@main_bp.route('/my_bookings')
@login_required
def my_bookings():
    page = request.args.get('page', 1, type=int)
    # Modify the query to paginate the bookings.
    paginated_bookings = Booking.query.filter_by(user_id=current_user.id).paginate(
        page=page, per_page=ROWS_PER_PAGE, error_out=False
    )
    return render_template('my_bookings.html', bookings=paginated_bookings, ROWS_PER_PAGE=ROWS_PER_PAGE)

website/templates/401.html
<!DOCTYPE html>
<html>
<head>
    <title>401 - Unauthorized</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <div class="error-page">
        <h1>401 - Unauthorized</h1>
        <p>You are not authorized to access this page <span class="colon">:(</span></p>
    </div>
</body>
</html>

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Event Management - Home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="styles.css">
</head>



    <nav>
    <!-- <body class="bg-dark text-light"> -->
        <!-- Navbar -->
        <!-- <body class="bg-light text-dark"> -->
         <!-- Nav-->
         <nav class="navbar navbar-expand-lg navbar-light bg-purple">
             <div class="container">
                 <a class="navbar-brand" href="/"><b>Music Event Page</b></a>
                 <div class="collapse navbar-collapse">
                     <ul class="navbar-nav">


                <!-- <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto"> -->
                        <!-- Register/Login/Logout and welcome -->
                        
                        {% if current_user.is_authenticated %}
                            
                            
                                <li class="nav-item">
                            <li class="nav-item">
                                <a class="nav-link" href="/my_bookings">Bookings</a>
                            </li>
                            
                                 <a class="nav-link" href="{{ url_for('event.create') }}">Create Event</a>
                              </li>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link disabled text-muted" href="#">Welcome {{current_user.name}}</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="/events">Events</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('auth.login') }}">Log In</a>
                            </li>
                            
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>

</body>

</html>

     
      <!-- flashes any messages to the user -->
      {% with messages = get_flashed_messages() %}
      {% if messages %} <!-- check if there are any messages -->
      <div class="container-fluid">
         <div class="row mt-3 mb-3">
            <div class="col-md-12">
            {% for message in messages %} <!--loop through the messages-->
            <div class="alert alert-info">{{ message }}</div> <!--display as alert-->
            {% endfor %}
         </div>
      </div>
      </div>
      {% endif %}
      {% endwith %}
    
      {% block header %}

      {% endblock %}

   </header>
      
   {% block content %}

   {% endblock %}
   
   <footer class="footer mt-auto py-3 bg-purple text-center">
      <div class="container">
          <p>&copy; 2023 Music Events</p>
      </div>
  </footer>
   </body>
   <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script> -->
</html>

website/templates/index.html
{% extends 'base.html' %}

<!DOCTYPE html>


<html lang="en">
  {% block header %}
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Eventify</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <link rel="stylesheet" href="../static/style.css" />
  </head>
  
  <body>
    <!-- Navbar -->
    <nav
      class="navbar navbar-expand-lg navbar-light bg-white"
    >
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand mx-auto" href="{{ url_for('main.index') }}">Eventify</a>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Browse by Category
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <!-- Dynamically generate dropdown items for each genre -->
                  {% for genre in genres %}
                  <a class="dropdown-item" href="{{ url_for('main.index', genre=genre) }}">{{ genre }}</a>
                  {% endfor %}
              </div>
          </li>
      </ul>
  </div>
  

      <form class="form-inline my-2 my-lg-0" action="{{ url_for('main.search') }}" method="get">
         <input class="form-control mr-sm-2" type="search" placeholder="Search events" aria-label="Search" name="search">
         <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
       </form>
        </ul>
      
      </div>
    </nav>
    {% endblock %}

  
    {% block content %}
    
    {% if search_query %}
    <div class="container mt-4">
      <h2>Search Results for "{{ search_query }}"</h2>
    </div>
    {% endif %}

    <section id="upcoming-events" class="container mt-4">
      <h2 class="upcoming-events-title">Eventify</h2>
      <h3 class="subhead">Display All Music Events Near You</h3>
      <h3 class="Eventify">Upcoming Events</h3>
      <!-- ... (Titles) ... -->


      <!-- Events Cards -->
      <div style="margin-bottom: 20px;"></div>
      <div class="row">
         {% for event in events %}
           <!-- Card -->
           <div class="col-md-4 mb-4">
             <div class="card">
              <img src="{{event.image}}" alt="{{event.name}}" class="card-img-top" />
              <div class="card-body">
                 <h5 class="card-title">{{ event.name }}</h5>
                 <p><strong>Date:</strong> {{ event.date.strftime("%B %d, %Y") }}</p>
                 <p><strong>Category:</strong> {{  event.genre }}</p>
                 <p>
                  <strong>Status:</strong> 
                  <span class="status {{ 'status-' + event.status | lower }}">{{ event.status }}</span>
                </p>
                 <a href="{{ url_for('event.show', id=event.id) }}" class="btn btn-primary">Details</a>
               </div>
             </div>
           </div>
           <!-- Checks if the index of the loop is a multiple of 3 (and not the first item) to end and start a new row -->
           {% if loop.index is divisibleby 3 and not loop.first %}
             </div>
             <div class="row">
           {% endif %}
         {% endfor %}
       </div>
     </section>

     <section id="browse-categories" class="container mt-5">
      <h3>Browse by Category</h3>
      <div class="row">
        <!-- First Row Category Cards -->
        <div class="col-md-3">
          <a href="{{ url_for('main.index', genre='Rock') }}" class="category-card">
            <h4>Rock</h4>
            <p>Feel the energy of rock music</p>
          </a>
        </div>
        <div class="col-md-3">
          <a href="{{ url_for('main.index', genre='Pop') }}" class="category-card">
            <h4>Pop</h4>
            <p>Catchy tunes and big hits</p>
          </a>
        </div>
        <div class="col-md-3">
          <a href="{{ url_for('main.index', genre='Hip-Hop') }}" class="category-card">
            <h4>Hip Hop</h4>
            <p>Beats and rhymes to groove to</p>
          </a>
        </div>
        <div class="col-md-3">
          <a href="{{ url_for('main.index', genre='Country') }}" class="category-card">
            <h4>Country</h4>
            <p>Stories and melodies from the heart</p>
          </a>
        </div>
      </div>
      <div class="row mt-3">
        <!-- Second Row Category Cards -->
        <div class="col-md-4">
          <a href="{{ url_for('main.index', genre='Jazz') }}" class="category-card">
            <h4>Jazz</h4>
            <p>Smooth sounds and improvisation</p>
          </a>
        </div>
        <div class="col-md-4">
          <a href="{{ url_for('main.index', genre='Blues') }}" class="category-card">
            <h4>Blues</h4>
            <p>The soul of music</p>
          </a>
        </div>
        <div class="col-md-4">
          <a href="{{ url_for('main.index', genre='Classical') }}" class="category-card">
            <h4>Classical</h4>
            <p>Timeless orchestral pieces</p>
          </a>
        </div>
      </div>
    </section>
    
  
      
        </section>
        <!-- Search Form Section -->
  
        <!-- Testimonials Section -->
        <section id="testimonials" class="container mt-5">
          <h4>What Our Users Say</h4>
          <div
            id="testimonial-carousel"
            class="carousel slide"
            data-ride="carousel"
          >
            <!-- Carousel items -->
            <div class="carousel-inner">
              <div class="carousel-item active">
                <blockquote class="testimonial">
                  <p>
                    "The best site to find and book music events! Easy to use and
                    reliable."
                  </p>
                  <quote>- Jane Doe, Music Enthusiast</quote>
                </blockquote>
              </div>
              <!-- More testimonials -->
               <!-- Testimonial 2 -->
          <div class="carousel-item">
              <blockquote class="testimonial">
                <p>
                  "A fantastic platform that has brought so many memorable evenings to life. Highly recommended!"
                </p>
                <quote>- John Smith, Concert Goer</quote>
              </blockquote>
            </div>
            <!-- Testimonial 3 -->
            <div class="carousel-item">
              <blockquote class="testimonial">
                <p>
                  "Amazing variety, great prices, and the customer service is top-notch!"
                </p>
                <quote>- Emily Clark, Festival Fanatic</quote>
              </blockquote>
            </div>
          </div>
            </div>
          </div>
        </section>
      </div>
  
  
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.9/dist/umd/popper.min.js"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
      <script src="{{ url_for('static', filename='jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='bootstrap.bundle.min.js') }}"></script>
    </body>
  </html>
  {% endblock %}

website/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login and Register</title>
    
</head>
<body>
    <div class="container">
        <div class="tabs">
            <div class="tab" onclick="showTab('login')">Login</div>
            <div class="tab" onclick="showTab('register')">Register</div>
        </div>
        <div class="content" id="loginContent">
            <h2>Login</h2>
            <form action="login.php" method="post">
                <div class="form-group">
                    <label for="loginUsername">Username:</label>
                    <input type="text" id="loginUsername" name="loginUsername" required>
                </div>
                <div class="form-group">
                    <label for="loginPassword">Password:</label>
                    <input type="password" id="loginPassword" name="loginPassword" required>
                </div>
                <button type="submit">Login</button>
            </form>
        </div>
        <div class="content" id="registerContent" style="display: none;">
            <h2>Register</h2>
            <form action="register.php" method="post">
                <div class="form-group">
                    <label for="registerUsername">Username:</label>
                    <input type="text" id="registerUsername" name="registerUsername" required>
                </div>
                <div class="form-group">
                    <label for="registerEmail">Email:</label>
                    <input type="email" id="registerEmail" name="registerEmail" required>
                </div>
                <div class="form-group">
                    <label for="registerPassword">Password:</label>
                    <input type="password" id="registerPassword" name="registerPassword" required>
                </div>
                <button type="submit">Register</button>
            </form>
        </div>
    </div>

    <script>
        function showTab(tabName) {
            if (tabName === 'login') {
                document.getElementById('loginContent').style.display = 'block';
                document.getElementById('registerContent').style.display = 'none';
            } else {
                document.getElementById('loginContent').style.display = 'none';
                document.getElementById('registerContent').style.display = 'block';
            }
        }
    </script>
</body>
</html>

website/templates/my_bookings.html
{% extends 'base.html' %}



{% block content %}

<link rel="stylesheet" href="../static/style.css" />

<!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"> -->



<div class="container mt-5">
    <h1 class="my-bookings-title">My Bookings</h1>
    <div class="card shadow-sm">
        <div class="card-book">
            <div class="table-responsive">
                <!-- Table that displays the users' booking history -->
                <table class="table table-bordered">
                    <thead class="bg-booking-header">
                        <tr>
                            <th scope="col">Booking ID</th>
                            <th scope="col">Name</th>
                            <th scope="col">Amount</th>
                            <th scope="col">Price</th>
                            <th scope="col">Event Name</th>
                            <th scope="col">Event Image</th>
                            <th scope="col">Booked On</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for booking in bookings.items %}
                        <tr>
                            <td>{{ booking.id }}</td>
                            <td>{{ booking.name }}</td>
                            <td>{{ booking.number_of_tickets }}</td>
                            <td>${{ booking.price_per_ticket}}</td>
                            <td>{{ booking.event.name }}</td>
                            <td>
                                <img src="{{ booking.event.image }}" alt="Event Image" style="max-width: 100px;">
                            </td>
                            <td>{{ booking.created_at.strftime("%B %d, %Y") }}</td>
                        </tr>
                        {% else %}
                        <tr>
                            <td colspan="7" class="text-center">No bookings found.</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            {% if bookings.total > 1 %}
            <nav aria-label="Booking navigation">
                <ul class="pagination justify-content-center">
                    {% if bookings.has_prev %}
                    <li class="page-item">
                        <a class="page-link" href="{{ url_for('main.my_bookings', page=1) }}" aria-label="First">
                            <span aria-hidden="true">First</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="{{ url_for('main.my_bookings', page=bookings.prev_num) }}" aria-label="Previous">
                            <span aria-hidden="true">Previous</span>
                        </a>
                    </li>
                    {% endif %}
                    {% for page in range(1, bookings.pages + 1) %}
                    <li class="page-item {% if page == bookings.page %}active{% endif %}">
                        <a class="page-link" href="{{ url_for('main.my_bookings', page=page) }}">{{ page }}</a>
                    </li>
                    {% endfor %}
                    {% if bookings.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="{{ url_for('main.my_bookings', page=bookings.next_num) }}" aria-label="Next">
                            <span aria-hidden="true">Next</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="{{ url_for('main.my_bookings', page=bookings.pages) }}" aria-label="Last">
                            <span aria-hidden="true">Last</span>
                        </a>
                    </li>
                    
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
            
        </div>
    </div>
    <div style="margin-bottom: 20px;"></div>
</div>


{% endblock %}

website/templates/user.html
{% extends 'base.html' %}
{% from "bootstrap5/form.html" import render_form %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">

<div class="container1">
    <div class="row mt-5 mb-3">
        <div class="col-md-12">
            <div class="float-left">
                <h1 class="mb-0"><center>{{ heading }}</center></h1>
            </div>
            <div class="float-right text-right">
            </div>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="page-header">
                <h4>{{ heading }}</h4>
            </div>
            {{ render_form(form) }}

            <!-- When you have a login form, show the user a link to register -->
            {% if heading|lower == 'login' %}
            <div class="row">
                <div class="col-md-12 text-center">
                    <p class="mt-3">New user? <a href="{{ url_for('auth.register') }}">Click here to register</a>.</p>
                    <div style="margin-bottom: 56%;"></div>
                </div>
            </div>
            {% endif %}
            <div style="margin-bottom: 14%;"></div>
        </div>
    </div>
</div>



{% endblock %}